### PR TITLE
Look and feel update

### PR DESCRIPTION
**Pull request by xcash-rocks**
# Description
Refactoring of code improving the layout, design, data visualization, user experience, SEO, etc. 

Demo: [http://delegates.xcash.rocks/](http://delegates.xcash.rocks)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

[http://delegates.xcash.rocks/](http://delegates.xcash.rocks)
  

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by zachhildreth** [comment]
Hi @xcash-rocks this looks REALLY good from the demo site!
dony worry about the sonarcloud bugs

I do have a few questions though


why on the demo site for our practice mainnet 1 does the
TOTAL VOTES
AVERAGE DELEGATE TOTAL VOTE
NEXT RECALCULATING OF VOTES

all show 0 and dont work, since they are working on the "official" delegates website

====

Can we remove the Verify Round Statistics from the help section, as this was a legacy CLI function and no longer a part of the wallet function (you can only use the website now to breakdown the data)

====

On the API page, is the URL a constant somewhere or do we need to change it if we run a mirror

====

On the API page for Get round statistics, it only has 1 param for blockheight no second param

====
On the API page, maybe we should use fetch API in JS for the JS snippet, instead of XHR request? as Fetch is the more modern es6 standard
https://javascript.info/fetch

====
On the API, why do none of the API work? 
for example visit in the browser
http://delegates.xcash.rocks/delegateswebsitegetstatistics
http://delegates.xcash.foundation/delegateswebsitegetstatistics

the official website will output JSON data, yet your website just redirects you back to the dashboard?



Thanks that is all the questions/problems I could find!

**Comment by xcash-rocks** [comment]
Hi @zachhildreth,

please see my reply in-line:

> dony worry about the sonarcloud bugs

too late but ok :-)
Could you extend the  "Quality Profile" for CSS and add custom ignoreTypes: `/^(mat|md|fa|cdk)-/` to the rule “Selectors should be known”(CSS RSPEC-4670) ?
See:[ how-to-change-css-rule-selectors-should-be-known](https://community.sonarsource.com/t/how-to-change-css-rule-selectors-should-be-known/31912/3) 

> ====
> why on the demo site for our practice mainnet 1 does the
> TOTAL VOTES
> AVERAGE DELEGATE TOTAL VOTE
> NEXT RECALCULATING OF VOTES
> all show 0 and dont work, since they are working on the "official" delegates website

Cannot reproduce, maybe I deployed at that moment, please recheck.
Please note that the demo site use "delegates.xcash.foundation" as API Endpoint.
See  [src/environments/environment.ts](https://github.com/xcash-rocks/delegates-explorer/blob/look-and-feel-update/src/environments/environment.ts#L3)
    
> ====
> Can we remove the Verify Round Statistics from the help section, as this was a legacy CLI function and no longer a part of the wallet function (you can only use the website now to breakdown the data)

Ok, done!

> ====
> On the API page, is the URL a constant somewhere or do we need to change it if we run a mirror
You can set the API-URL in the environment. The baseURL is used for the API Examples.
See  [src/environments/environment.prod.ts](https://github.com/xcash-rocks/delegates-explorer/blob/look-and-feel-update/src/environments/environment.prod.ts)


> ====
> On the API page for Get round statistics, it only has 1 param for blockheight no second param

Ups, just a test, forgot to delete. Done.


> ====
> On the API page, maybe we should use fetch API in JS for the JS snippet, instead of XHR request? as Fetch is the more modern es6 standard
> https://javascript.info/fetch

Will add the ES6 Snippet and keep the XHR request for nostalgia :-)


> ====
> On the API, why do none of the API work?
> for example visit in the browser
> http://delegates.xcash.rocks/delegateswebsitegetstatistics
> http://delegates.xcash.foundation/delegateswebsitegetstatistics
> the official website will output JSON data, yet your website just redirects you back to the dashboard?

The demo site use "delegates.xcash.foundation" as API Endpoint, the demo server is not running the xcash-dpops delegates_website sockets.

**Comment by xcash-rocks** [comment]
Hi @zachhildreth,

> why on the demo site for our practice mainnet 1 does the
> TOTAL VOTES
> AVERAGE DELEGATE TOTAL VOTE
> NEXT RECALCULATING OF VOTES
> 
> all show 0 and dont work, since they are working on the "official" delegates website

FYI: now I am having the same issue!

**Comment by xcash-rocks** [comment]
Hi @zachhildreth!

FYI: Fixed the dashcards in dashboard.


> > TOTAL VOTES
> > AVERAGE DELEGATE TOTAL VOTE
> > NEXT RECALCULATING OF VOTES

**Comment by zachhildreth** [comment]
Thank you @xcash-rocks 
I will add the sonar cloud rule tomorrow then!

I think code wise everything was explained or fixed then? Makes sense for some of the answers if the delegate website option is not running on your delegate

I will try to rebuild it soon on the delegates website, and look over the code commits more closely over the next days and post any more questions if I see something, but it looks good at this point!

**Comment by xcash-rocks** [comment]
All issues fixed and requested improvements added.
Ready to merge that PR! 

> Thank you @xcash-rocks
> I will add the sonar cloud rule tomorrow then!
> 
> I think code wise everything was explained or fixed then? Makes sense for some of the answers if the delegate website option is not running on your delegate
> 
> I will try to rebuild it soon on the delegates website, and look over the code commits more closely over the next days and post any more questions if I see something, but it looks good at this point!

**Pull request merged**
